-   id: make-executable
    name: Make scripts executable
    description: This hook ensures scripts have execute permissions
    entry: python3 hooks/make_executable.py
    language: python
-   id: secret-scanner
    name: Scan for secrets
    description: This hook scans for secrets
    entry: hooks/secrets.sh 
    language: script
-   id: sast-scanner
    name: Sast scan
    description: Static application security testing
    entry: hooks/sast.sh 
    language: script