-   id: secret-scanner
    name: 'Scan for secrets'
    description: 'This hook scans for secrets'
    entry: hooks/secrets.sh 
    language: 'script'
    args: ["."]
-   id: sast-scanner
    name: 'Sast scan'
    description: 'Static application security testing'
    entry: hooks/sast.sh 
    language: 'script'
    args: ["."]